language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

env:
    - YAML=symfony
    - YAML=spyc
    - YAML=extension

matrix:
    allow_failures:
        - php: hhvm-nightly
    fast_finish: true

before_script:
    - phpenv version-name
    - composer install --prefer-source
    - sh -c "if [ '$YAML' = 'symfony' ]; then echo ''; fi"
    - sh -c "if [ '$YAML' = 'spyc' ]; then composer require mustangostang/spyc:~0.5.0; fi"
    - sh -c "if [ '$YAML' = 'extension' ]; then pecl install yaml; fi"
    - sh -c "if [ '$YAML' = 'extension' ]; echo 'extension=<extension>.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"

script: ./vendor/bin/phpunit --coverage-text

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ebaba92b4cc7bca39419
    on_success: always
    on_failure: always
    on_start: false
